### ISSUE TITLE
Doesn't work with Spark 3.0

### ISSUE THREAD

**Issue by rajkve** [Azure/azure-sqldb-spark#83] opened 2020-07-02 05:31 UTC
This connector doesn't work with Spark 3.0 (SCALA 12) - 

Error message: Invalid scala product class

**Comment by arvindshmicrosoft** [comment] 2020-07-02 20:54
Thank you for your question. This is a duplicate of #80 - repeating the text from that issue:

> There are no plans to support Spark 3.0.0 with this connector. Consider evaluating the 
> [Apache Spark Connector for SQL Server and Azure SQL](https://github.com/microsoft/sql-spark-connector) which is a newer connector. They are already tracking [the request](https://github.com/microsoft/sql-spark-connector/issues/15) for Spark 3.0.0 support in the new connector.

I am closing this issue as there are no plans to address this request in this connector.

**Closed by arvindshmicrosoft** 2020-07-02 20:54 UTC

**Comment by rajkve** [comment] 2020-07-03 13:04
Hi - I am not quite sure if using [this](https://github.com/microsoft/sql-spark-connector) connector is an option, based on our performance testing - this connector is 4X slower for the same configuration
