### ISSUE TITLE
com.microsoft.sqlserver.jdbc.SQLServerException: Unable to retrieve data from the source.

### ISSUE THREAD

**Issue by ronbuchanan** [Azure/azure-sqldb-spark#19] opened 2018-09-07 23:06 UTC
Running inside Databricks environment on Azure. The jar is loaded and recognized.

I have followed the example for bulk copy, just changing out the parameters. The target table has an `IDENTITY` column, but the source file does not.

The Dataframe has data, I have verified with `display(...)`.

 Everything runs except `bulkCopyToSqlDB(...)`. I get the following exception:

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 3 in stage 14.0 failed 4 times, most recent failure: Lost task 3.3 in stage 14.0 (TID 308, 10.139.64.8, executor 1): com.microsoft.sqlserver.jdbc.SQLServerException: Unable to retrieve data from the source.
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeBatchData(SQLServerBulkCopy.java:3268)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.doInsertBulk(SQLServerBulkCopy.java:1570)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.access$200(SQLServerBulkCopy.java:58)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy$1InsertBulk.doExecute(SQLServerBulkCopy.java:709)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7151)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2478)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.sendBulkLoadBCP(SQLServerBulkCopy.java:739)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(SQLServerBulkCopy.java:1684)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(SQLServerBulkCopy.java:669)
	at com.microsoft.azure.sqldb.spark.connect.DataFrameFunctions.com$microsoft$azure$sqldb$spark$connect$DataFrameFunctions$$bulkCopy(DataFrameFunctions.scala:100)
	at com.microsoft.azure.sqldb.spark.connect.DataFrameFunctions$$anonfun$bulkCopyToSqlDB$1.apply(DataFrameFunctions.scala:47)
	at com.microsoft.azure.sqldb.spark.connect.DataFrameFunctions$$anonfun$bulkCopyToSqlDB$1.apply(DataFrameFunctions.scala:47)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:941)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:941)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2180)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2180)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:112)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:384)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

**Comment by eparizzi** [comment] 2019-06-13 23:36
Getting the same error. Any updates?

**Comment by InterruptSpeed** [comment] 2019-09-06 18:45
just encountered this error myself. source is parquet data stored in data lake storage. code has been very happy to load other files from the same storage against the same db but not this one. parquet file[s] are in /parquet/DOCUMENT/ and nothing special exists on the path in terms of access controls. was suspicious that there was a reserved keyword in the mix here somewhere but i can't find it. using azure-sqldb-spark 1.0.2 on a Standard DS3 v2 cluster running 5.5 LTS runtime.

**Comment by InterruptSpeed** [comment] 2019-09-11 12:36
managed to overcome this issue. root cause was having a target table already defined that had more columns than my source file as loaded into the dataframe. certainly the exception message isn't helpful...but fixing the target table sorted me right out.

**Comment by arvindshmicrosoft** [comment] 2020-09-03 22:42
Before closing this issue, I thought I'd share a sample to address the IDENTITY column requirement. First, read in the departure delays dataset:
``` scala
val df = spark.read.format("com.databricks.spark.csv").option("header", "true").
  option("inferschema", "true").load("dbfs:/databricks-datasets/flights/departuredelays.csv")
display(df)
```
The SQL table for this is:
``` sql
create table departuredelays
(
	id bigint identity not null,
	fltdate int,
	delaymin int,
	distance int,
	origin char(3),
	destination char(3)
)
```
Next, create a new dataframe with a fake identity column:
``` scala
val df_with_fake_ident = df.withColumn("id", lit(0)).select("id", "date", "delay", "distance", "origin", "destination")
df_with_fake_ident.printSchema
display(df_with_fake_ident)
```
Then, proceed to import to SQL DB. This will effectively ignore the fake identity column from the dataframe, and have SQL generate the required identity values.
``` scala
import com.microsoft.azure.sqldb.spark.bulkcopy.BulkCopyMetadata
import com.microsoft.azure.sqldb.spark.config.Config
import com.microsoft.azure.sqldb.spark.connect._
import org.apache.spark.sql.functions._

var bulkCopyMetadata = new BulkCopyMetadata
bulkCopyMetadata.addColumnMetadata(1, "id", java.sql.Types.INTEGER, 4, 0)
bulkCopyMetadata.addColumnMetadata(2, "fltdate", java.sql.Types.INTEGER, 4, 0)
bulkCopyMetadata.addColumnMetadata(3, "delaymin", java.sql.Types.INTEGER, 4, 0)
bulkCopyMetadata.addColumnMetadata(4, "distance", java.sql.Types.INTEGER, 4, 0)
bulkCopyMetadata.addColumnMetadata(5, "origin", java.sql.Types.CHAR, 3, 0)
bulkCopyMetadata.addColumnMetadata(6, "destination", java.sql.Types.CHAR, 3, 0)

val bulkCopyConfig = Config(Map(
  "url"               -> "SOMESVR.database.windows.net",
  "databaseName"      -> "SOMEDB",
  "user"              -> "SOMEUSER",
  "password"          -> "SOMEPASSWORD",
  "dbTable"           -> "dbo.departuredelays",
  "bulkCopyBatchSize" -> "2500",
  "bulkCopyTableLock" -> "true",
  "bulkCopyTimeout"   -> "600"
))

df_with_fake_ident.limit(100).bulkCopyToSqlDB(bulkCopyConfig, bulkCopyMetadata)
```
If you want to keep the value from Spark and populate the IDENTITY column with that same value, use bulkCopyKeepIdentity in the bulkCopyConfig as shown below:
``` scala
val df_with_real_ident = df.withColumn("id", monotonically_increasing_id()).select("id", "date", "delay", "distance", "origin", "destination")
display(df_with_real_ident)

import com.microsoft.azure.sqldb.spark.bulkcopy.BulkCopyMetadata
import com.microsoft.azure.sqldb.spark.config.Config
import com.microsoft.azure.sqldb.spark.connect._
import org.apache.spark.sql.functions._

var bulkCopyMetadata = new BulkCopyMetadata
bulkCopyMetadata.addColumnMetadata(1, "id", java.sql.Types.BIGINT, 4, 0)
bulkCopyMetadata.addColumnMetadata(2, "fltdate", java.sql.Types.INTEGER, 4, 0)
bulkCopyMetadata.addColumnMetadata(3, "delaymin", java.sql.Types.INTEGER, 4, 0)
bulkCopyMetadata.addColumnMetadata(4, "distance", java.sql.Types.INTEGER, 4, 0)
bulkCopyMetadata.addColumnMetadata(5, "origin", java.sql.Types.CHAR, 3, 0)
bulkCopyMetadata.addColumnMetadata(6, "destination", java.sql.Types.CHAR, 3, 0)

val bulkCopyConfig = Config(Map(
  "url"               -> "SOMESVR.database.windows.net",
  "databaseName"      -> "SOMEDB",
  "user"              -> "SOMEUSER",
  "password"          -> "SOMEPASSWORD",
  "dbTable"           -> "dbo.departuredelays",
  "bulkCopyKeepIdentity"      -> "true",
  "bulkCopyBatchSize" -> "2500",
  "bulkCopyTableLock" -> "true",
  "bulkCopyTimeout"   -> "600"
))

df_with_real_ident.limit(100).bulkCopyToSqlDB(bulkCopyConfig, bulkCopyMetadata)
```
Also linking to #48 which has similar discussion topic.

**Closed by arvindshmicrosoft** 2020-09-03 22:42 UTC
